# Generated by Django 6.0.6 on 2026-07-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoEstresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estudante', models.CharField(blank=True, max_length=150, verbose_name='Nome (opcional)')),
                ('horas_sono', models.FloatField(help_text='Média de horas dormidas por noite.', verbose_name='Horas de sono por noite')),
                ('carga_estudo', models.PositiveSmallIntegerField(help_text='Quantidade de horas dedicadas aos estudos por dia.', verbose_name='Carga diária de estudos (horas)')),
                ('frequencia_dor_cabeca', models.PositiveSmallIntegerField(help_text='0 = nunca, 5 = quase todos os dias.', verbose_name='Frequência de dores de cabeça (0 a 5)')),
                ('nivel_atividade_fisica', models.PositiveSmallIntegerField(help_text='0 = sedentário, 5 = muito ativo.', verbose_name='Nível de atividade física (0 a 5)')),
                ('qualidade_sono', models.PositiveSmallIntegerField(help_text='0 = péssima, 5 = excelente.', verbose_name='Qualidade percebida do sono (0 a 5)')),
                ('nivel_ansiedade', models.PositiveSmallIntegerField(help_text='0 = nenhuma, 5 = extrema.', verbose_name='Nível de ansiedade percebido (0 a 5)')),
                ('pressao_prazos', models.PositiveSmallIntegerField(help_text='0 = nenhuma, 5 = extrema.', verbose_name='Pressão por prazos acadêmicos (0 a 5)')),
                ('frequencia_cansaco', models.PositiveSmallIntegerField(help_text='0 = nunca, 5 = sempre.', verbose_name='Frequência de cansaço (0 a 5)')),
                ('nivel_estresse_previsto', models.CharField(blank=True, choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], max_length=10, verbose_name='Nível de estresse previsto')),
                ('mensagem_explicativa', models.TextField(blank=True, verbose_name='Mensagem explicativa')),
                ('score_confianca', models.FloatField(blank=True, null=True, verbose_name='Confiança da predição (0 a 1)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Avaliação de Estresse',
                'verbose_name_plural': 'Avaliações de Estresse',
                'ordering': ['-criado_em'],
            },
        ),
    ]
