# Generated by Django 6.0.6 on 2026-07-05 01:57

import core.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('ESTUDANTE', 'Estudante'), ('UNIVERSIDADE', 'Universidade')], max_length=15, verbose_name='Role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoEstresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estudante', models.CharField(blank=True, max_length=150, verbose_name='Nome (opcional)')),
                ('horas_sono', models.FloatField(help_text='Média de horas dormidas por noite.', verbose_name='Horas de sono por noite')),
                ('carga_estudo', models.PositiveSmallIntegerField(help_text='Quantidade de horas dedicadas aos estudos por dia.', verbose_name='Carga diária de estudos (horas)')),
                ('frequencia_dor_cabeca', models.PositiveSmallIntegerField(help_text='0 = nunca, 5 = quase todos os dias.', verbose_name='Frequência de dores de cabeça (0 a 5)')),
                ('nivel_atividade_fisica', models.PositiveSmallIntegerField(help_text='0 = sedentário, 5 = muito ativo.', verbose_name='Nível de atividade física (0 a 5)')),
                ('qualidade_sono', models.PositiveSmallIntegerField(help_text='0 = péssima, 5 = excelente.', verbose_name='Qualidade percebida do sono (0 a 5)')),
                ('nivel_ansiedade', models.PositiveSmallIntegerField(help_text='0 = nenhuma, 5 = extrema.', verbose_name='Nível de ansiedade percebido (0 a 5)')),
                ('pressao_prazos', models.PositiveSmallIntegerField(help_text='0 = nenhuma, 5 = extrema.', verbose_name='Pressão por prazos acadêmicos (0 a 5)')),
                ('frequencia_cansaco', models.PositiveSmallIntegerField(help_text='0 = nunca, 5 = sempre.', verbose_name='Frequência de cansaço (0 a 5)')),
                ('nivel_estresse_previsto', models.CharField(blank=True, choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], max_length=10, verbose_name='Nível de estresse previsto')),
                ('mensagem_explicativa', models.TextField(blank=True, verbose_name='Mensagem explicativa')),
                ('score_confianca', models.FloatField(blank=True, null=True, verbose_name='Confiança da predição (0 a 1)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('estudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de Estresse',
                'verbose_name_plural': 'Avaliações de Estresse',
                'ordering': ['-criado_em'],
            },
        ),
    ]
