# Generated by Django 6.0.6 on 2026-07-05 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='carga_estudo',
            field=models.PositiveSmallIntegerField(verbose_name='Carga diária de estudos (horas)'),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='frequencia_cansaco',
            field=models.PositiveSmallIntegerField(verbose_name='Frequência de cansaço (0 a 5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='frequencia_dor_cabeca',
            field=models.PositiveSmallIntegerField(verbose_name='Frequência de dores de cabeça (0 a 5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='horas_sono',
            field=models.FloatField(verbose_name='Horas de sono por noite'),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='mensagem_explicativa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='nivel_ansiedade',
            field=models.PositiveSmallIntegerField(verbose_name='Nível de ansiedade percebido (0 a 5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='nivel_atividade_fisica',
            field=models.PositiveSmallIntegerField(verbose_name='Nível de atividade física (0 a 5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='nivel_estresse_previsto',
            field=models.CharField(blank=True, choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='pressao_prazos',
            field=models.PositiveSmallIntegerField(verbose_name='Pressão por prazos acadêmicos (0 a 5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='qualidade_sono',
            field=models.PositiveSmallIntegerField(verbose_name='Qualidade percebida do sono (0 a 5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaoestresse',
            name='score_confianca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FormularioGerado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_gerados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulário Gerado',
                'verbose_name_plural': 'Formulários Gerados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('turma', models.CharField(max_length=100, verbose_name='Turma/Ano escolar')),
                ('anxiety_level', models.PositiveSmallIntegerField(verbose_name='Nível de ansiedade')),
                ('self_esteem', models.PositiveSmallIntegerField(verbose_name='Autoestima')),
                ('mental_health_history', models.PositiveSmallIntegerField(verbose_name='Histórico de saúde mental')),
                ('depression', models.PositiveSmallIntegerField(verbose_name='Depressão')),
                ('headache', models.PositiveSmallIntegerField(verbose_name='Dor de cabeça')),
                ('blood_pressure', models.PositiveSmallIntegerField(verbose_name='Pressão arterial')),
                ('sleep_quality', models.PositiveSmallIntegerField(verbose_name='Qualidade do sono')),
                ('breathing_problem', models.PositiveSmallIntegerField(verbose_name='Problemas respiratórios')),
                ('noise_level', models.PositiveSmallIntegerField(verbose_name='Nível de ruído')),
                ('living_conditions', models.PositiveSmallIntegerField(verbose_name='Condições de moradia')),
                ('safety', models.PositiveSmallIntegerField(verbose_name='Segurança')),
                ('basic_needs', models.PositiveSmallIntegerField(verbose_name='Necessidades básicas')),
                ('academic_performance', models.PositiveSmallIntegerField(verbose_name='Desempenho acadêmico')),
                ('study_load', models.PositiveSmallIntegerField(verbose_name='Carga de estudos')),
                ('teacher_student_relationship', models.PositiveSmallIntegerField(verbose_name='Relação professor-aluno')),
                ('future_career_concerns', models.PositiveSmallIntegerField(verbose_name='Preocupações com carreira')),
                ('social_support', models.PositiveSmallIntegerField(verbose_name='Suporte social')),
                ('peer_pressure', models.PositiveSmallIntegerField(verbose_name='Pressão dos colegas')),
                ('extracurricular_activities', models.PositiveSmallIntegerField(verbose_name='Atividades extracurriculares')),
                ('bullying', models.PositiveSmallIntegerField(verbose_name='Bullying')),
                ('nivel_estresse_predito', models.IntegerField(blank=True, null=True, verbose_name='Nível de estresse predito (0-2)')),
                ('nivel_risco', models.CharField(blank=True, choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto')], max_length=50, verbose_name='Nível de risco')),
                ('data_submissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de submissão')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.formulariogerado')),
            ],
            options={
                'verbose_name': 'Resposta de Estudante',
                'verbose_name_plural': 'Respostas de Estudantes',
                'ordering': ['-data_submissao'],
            },
        ),
    ]
