# Generated by Django 6.0.6 on 2026-07-05 02:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_avaliacaoestresse_carga_estudo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaestudante',
            name='idade',
        ),
        migrations.AddField(
            model_name='formulariogerado',
            name='validade',
            field=models.DateTimeField(default=core.models.duas_semanas, verbose_name='Válido até'),
        ),
        migrations.AddField(
            model_name='respostaestudante',
            name='ra',
            field=models.CharField(default='', max_length=20, verbose_name='RA (Registro Acadêmico)'),
        ),
    ]
